yyj/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import PasswordChangeView

from . import views

app_name = 'yyj'
urlpatterns = [
    path('', views.index, name='yyj.index'),
    path('musical/', views.musical_index, name='yyj.musical_index'),
    path('artist/<int:pk>/', views.artist_detail, name='yyj.artist_detail'),
    path('artist/<int:pk>/show', views.artist_show_index, name='yyj.artist_show_index'),
    path('artist/<int:pk>/download', views.artist_show_download, name='yyj.artist_show_download'),
    path('musical/<int:pk>/', views.musical_detail, name='yyj.musical_detail'),
    path('produce/<int:pk>/', views.produce_detail, name='yyj.produce_detail'),
    path('tour/<int:pk>/', views.tour_detail, name='yyj.tour_detail'),
    path('schedule/<int:pk>/', views.schedule_detail, name='yyj.schedule_detail'),
    path('schedule/<int:pk>/show', views.schedule_show_index, name='yyj.schedule_show_index'),
    path('city/<int:pk>/', views.city_detail, name='yyj.city_detail'),
    path('theatre/<int:pk>/', views.theatre_detail, name='yyj.theatre_detail'),
    path('theatre/<int:pk>/show', views.theatre_show_index, name='yyj.theatre_show_index'),
    path('stage/', views.stage_index, name='yyj.stage_index'),
    path('stage/<int:pk>/', views.stage_detail, name='yyj.stage_detail'),
    path('stage/<int:pk>/show', views.stage_show_index, name='yyj.stage_show_index'),
    path('location_map/', views.location_index_map, name='yyj.location_index_map'),
    path('location/<int:pk>/', views.location_detail, name='yyj.location_detail'),
    path('location/<int:pk>/map', views.location_map, name='yyj.location_map'),
    path('year/<int:year>/', views.show_year_index, name='yyj.show_year_index'),
    path('year/<int:year>/city', views.show_year_index_city, name='yyj.show_year_index_city'),
    path('year/<int:year>/artist', views.show_year_index_artist, name='yyj.show_year_index_artist'),
    path('search/', views.search, name='yyj.search'),
    path('search_day/', views.show_day_index, name='yyj.show_day_index'),
    path('search_day_map/', views.show_day_map, name='yyj.show_day_map'),
    path('download/', views.download, name='yyj.download'),
    path('download/<str:file>', views.download_file, name='yyj.download_file'),
    path('data/', TemplateView.as_view(template_name="yyj/data.html"), name='yyj.data'),
    path('api/', TemplateView.as_view(template_name="yyj/api.html"), name='yyj.api'),
    path('api/search_day/', views.api_show_day_index, name='yyj.api_show_day_index'),
    path('api/search_musical_show/', views.api_musical_show_index, name='yyj.api_musical_show_index'),
    path('api/artist/', views.api_artist_index, name='api_artist_index'),
    path('api/city/', views.api_city_index, name='api_city_index'),
    path('api/musical/', views.api_musical_index, name='api_musical_index'),
    path('api/musicalproduces/', views.api_musicalproduces_index, name='api_musicalproduces_index'),
    path('api/musicalstaff/', views.api_musicalstaff_index, name='api_musicalstaff_index'),
    path('api/musicalcast/', views.api_musicalcast_index, name='api_musicalcast_index'),
    path('api/produce/', views.api_produce_index, name='api_produce_index'),
    path('api/role/', views.api_role_index, name='api_role_index'),
    path('api/schedule/', views.api_schedule_index, name='api_schedule_index'),
    path('api/schedule/<int:pk>/show/', views.api_schedule_show_index, name='api_schedule_show_index'),
    path('api/show/<int:pk>/cast/', views.api_show_cast_index, name='api_show_cast_index'),
    path('api/stage/', views.api_stage_index, name='api_stage_index'),
    path('api/theatre/', views.api_theatre_index, name='api_theatre_index'),
    path('api/location/', views.api_location_index, name='api_location_index'),
    path('api/tour/', views.api_tour_index, name='api_tour_index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_change/', PasswordChangeView.as_view(success_url=reverse_lazy('yyj:password_change_done')), name='password_change'),
    path('accounts/register', views.register, name='register'),
    path('chupiao/', views.chupiao_index, name='yyj.chupiao_index'),
    path('chupiao/<int:pk>/', views.chupiao_detail, name='yyj.chupiao_detail'),
    path('chupiao/search', views.chupiao_search, name='yyj.chupiao_search'),
    path('chupiao/add/', views.chupiao_create, name='yyj.chupiao_add'),
    path('chupiao/<int:pk>/edit/', views.chupiao_edit, name='yyj.chupiao_edit'),
    path('chupiao/<int:pk>/delete/', views.chupiao_delete, name='yyj.chupiao_delete'),
    path('donation/', TemplateView.as_view(template_name="yyj/donation.html"), name='yyj.donation')
]

yyj/models.py
from django.db import models
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=20, unique=True)
    seq = models.PositiveSmallIntegerField(default=999)

    def get_absolute_url(self):
        return "/yyj/city/%i/" % self.id

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=50, unique=True)
    longitude = models.FloatField()  # 经度
    latitude = models.FloatField()  # 纬度

    def get_absolute_url(self):
        return "/yyj/location/%i/" % self.id

    def __str__(self):
        return self.name


class Theatre(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return "/yyj/theatre/%i/" % self.id

    def __str__(self):
        return self.name


class Stage(models.Model):
    theatre = models.ForeignKey(Theatre, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank=True)
    seats = models.PositiveSmallIntegerField(default=0)

    def get_absolute_url(self):
        return "/yyj/stage/%i/" % self.id

    def __str__(self):
        if self.name:
            return self.theatre.__str__() + self.name
        else:
            return self.theatre.__str__()


class Produce(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def get_absolute_url(self):
        return "/yyj/produce/%i/" % self.id

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=50)
    note = models.CharField(max_length=50, blank=True, null=True)

    def get_absolute_url(self):
        return "/yyj/artist/%i/" % self.id

    def __str__(self):
        if self.note:
            return self.name + self.note
        else:
            return self.name


class Musical(models.Model):
    produces = models.ManyToManyField(Produce, through='MusicalProduces')
    name = models.CharField(max_length=50, unique=True)
    is_original = models.BooleanField(default=True)
    SETUP = 'ZZ'
    PROMOTE = 'DD'
    PRESENT = 'SS'
    PROGRESS_CHOICES = [
        (SETUP, '制作'),
        (PROMOTE, '定档'),
        (PRESENT, '上演'),
    ]
    progress = models.CharField(
        max_length=2,
        choices=PROGRESS_CHOICES,
        default=SETUP,
    )
    premiere_date = models.DateField()
    premiere_date_text = models.CharField(max_length=20, blank=True, null=True)
    info = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return "/yyj/musical/%i/" % self.id

    def __str__(self):
        return self.name


class MusicalProduces(models.Model):
    musical = models.ForeignKey(Musical, on_delete=models.CASCADE)
    seq = models.PositiveSmallIntegerField(default=1)
    title = models.CharField(max_length=20, default="出品制作")
    produce = models.ForeignKey(Produce, on_delete=models.CASCADE)

    def __str__(self):
        return self.musical.name + self.title + self.produce.name


class MusicalStaff(models.Model):
    musical = models.ForeignKey(Musical, on_delete=models.CASCADE)
    seq = models.PositiveSmallIntegerField(default=1)
    job = models.CharField(max_length=50)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.musical.name + self.job + self.artist.name


class Role(models.Model):
    musical = models.ForeignKey(Musical, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    seq = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.seq.__str__() + ' ' + self.name


class MusicalCast(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    seq = models.PositiveSmallIntegerField(default=1)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('role', 'artist')

    def __str__(self):
        return self.role.seq.__str__() + ' ' + self.role.name + ' ' + self.seq.__str__() + ' ' + self.artist.name


class Tour(models.Model):
    musical = models.ForeignKey(Musical, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank=True)
    is_long_term = models.BooleanField(default=False)
    begin_date = models.DateField()
    end_date = models.DateField()

    def get_absolute_url(self):
        return "/yyj/tour/%i/" % self.id

    def __str__(self):
        if self.name:
            return self.musical.name + self.name
        else:
            return self.musical.name


class Schedule(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    is_long_term = models.BooleanField(default=False)
    begin_date = models.DateField()
    end_date = models.DateField()
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "/yyj/schedule/%i/" % self.id

    def __str__(self):
        return self.tour.__str__() + ' ' + self.begin_date.__str__() \
               + ' ' + self.end_date.__str__() + ' ' + self.stage.__str__()


class Show(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    time = models.DateTimeField()
    cast = models.ManyToManyField(MusicalCast, blank=True)

    def __str__(self):
        return self.schedule.__str__() + ' ' + self.time.__str__()


class Conflict(models.Model):
    time = models.DateTimeField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.time.__str__() + ' ' + self.artist.__str__()


class Chupiao(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    par_value = models.DecimalField(max_digits=6, decimal_places=2)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    seat = models.CharField(max_length=100)
    xianyu = models.TextField()
    note = models.CharField(max_length=100, null=True, blank=True)

    def get_absolute_url(self):
        return "/yyj/chupiao/%i/" % self.id

    def __str__(self):
        return self.user.__str__() + ' ' + self.show.__str__()

yyj/forms.py
from django import forms
from .models import City, Chupiao


class ShowForm(forms.Form):
    date = forms.DateField()
    city = forms.ModelChoiceField(required=False, queryset=City.objects.order_by('seq'))


class ApiShowDayForm(forms.Form):
    date = forms.DateField()
    city = forms.CharField(required=False, max_length=100)


class ApiMusicalShowForm(forms.Form):
    musical = forms.CharField(max_length=100)
    begin_date = forms.DateField()
    end_date = forms.DateField()


class ChupiaoSearchForm(forms.Form):
    keyword = forms.CharField(label='音乐剧', max_length=100)
    date = forms.DateField(label='日期')


class ChupiaoFilterForm(forms.Form):
    keyword = forms.CharField(required=False, label='音乐剧', max_length=100)


class ChupiaoForm(forms.ModelForm):
    class Meta:
        model = Chupiao
        fields = ['show', 'par_value', 'seat', 'price', 'xianyu', 'note']

    def clean(self):
        cleaned_data = super().clean()
        par_value = cleaned_data.get("par_value")
        price = cleaned_data.get("price")

        if price > par_value:
            msg = "出票价格不能高于票面价格。"
            self.add_error('price', msg)

yyj/templates/yyj/artist_show_index.html
{% extends "yyj/base.html" %}

{% block title %}{{ artist.name }}过往演出{% endblock %}

{% block content %}
<div class="ui basic segment">
    <h2 class="ui header"><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></h2>
</div>
{% if show_list %}
<div class="ui basic segment">
    <h3 class="ui pink header">
        过往演出
        {% if other %}
        <a href="?page={{ show_list.number }}&other=0" class="ui pink right floated basic button">不显示同场演员</a>
        {% else %}
        <a href="?page={{ show_list.number }}&other=1" class="ui pink right floated basic button">显示同场演员</a>
        {% endif %}
    </h3>
</div>
<table class="ui striped celled pink unstackable compact table">
    <thead>
        <tr>
            <th class="center aligned">时间</th>
            <th class="center aligned">音乐剧</th>
            <th class="center aligned">角色</th>
            {% if other %}<th class="center aligned">同场演员</th>{% endif %}
            <th class="center aligned">剧院</th>
        </tr>
    </thead>
    <tbody>
        {% for show in show_list %}
        <tr>
            <td class="center aligned">
                {% ifchanged show.time.date %}{{ show.time|date }} {{ show.time|date:"l" }}{% endifchanged %}
                {{ show.time|time }}
            </td>
            <td class="center aligned">
                <h4 class="ui header"><a href="{{ show.role.musical.get_absolute_url }}">{{ show.role.musical.name }}</a></h4>
            </td>
            <td class="center aligned">
                {{ show.role.name }}
            </td>
            {% if other %}
            <td>
                {% for cast in show.other_cast %}
                <a href="{{ cast.artist.get_absolute_url }}">{{ cast.artist.name }}</a>
                {% endfor %}
            </td>
            {% endif %}
            <td class="center aligned">
                <a href="{{ show.schedule.stage.theatre.city.get_absolute_url }}">
                    {{ show.schedule.stage.theatre.city.name }}
                </a>
                <a href="{{ show.schedule.stage.get_absolute_url }}">
                    {{ show.schedule.stage.theatre.name }}{{ show.schedule.stage.name|default_if_none:"" }}
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if show_list.paginator.num_pages > 1 %}
<div class="ui pagination menu">
    {% if show_list.has_previous %}
        <a href="?page=1" class="item"><i class="step backward icon"></i></a>
        <a href="?page={{ show_list.previous_page_number }}" class="item"><i class="chevron left icon"></i></a>
    {% endif %}
    <a href="?page={{ show_list.number }}" class="active item">{{ show_list.number }}</a>
    {% if show_list.has_next %}
        <a href="?page={{ show_list.next_page_number }}" class="item"><i class="chevron right icon"></i></a>
        <a href="?page={{ show_list.paginator.num_pages }}" class="item"><i class="step forward icon"></i></a>
    {% endif %}
</div>
{% endif %}
{% endif %}
{% endblock %}

yyj/templates/yyj/chupiao_add.html
{% extends "yyj/base.html" %}

{% block title %}添加出票信息{% endblock %}

{% block content %}
<div class="ui basic segment">
    <h3 class="ui pink header">添加出票信息</h3>
    {% for field in form %}
        {% if field.errors %}
            <div class="ui negative message">{{ field.errors }}</div>
        {% endif %}
    {% endfor %}
    <form class="ui form" action="{% url 'yyj:yyj.chupiao_add' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="show" value="{{ show.id }}">
        <h5>音乐剧：{{ show.schedule.tour.musical.name }}</h5>
        <h5>时间：{{ show.time }}</h5>
        <h5>剧院：{{ show.schedule.stage.theatre.city.name }} {{ show.schedule.stage.theatre.name }}{{ show.schedule.stage.name|default_if_none:"" }}</h5>
        <h5>卡司：{% for show_cast in show.cast_list %}{{ show_cast.artist.name }} {% endfor %}</h5>
        <div class="inline field">
            <label>票面价格（元）：</label>
            <input type="number" name="par_value" step="1" id="id_par_value" placeholder="0.00" value="{{ form.cleaned_data.par_value|default_if_none:'' }}" required>
        </div>
        <div class="inline field">
            <label>出票价格（元）：</label>
            <input type="number" name="price" step="1" id="id_price" placeholder="0.00" value="{{ form.cleaned_data.price|default_if_none:'' }}" required>
        </div>
        <div class="field">
            <label>座位信息：</label>
            {{ form.seat }}
        </div>
        <div class="field">
            <label>闲鱼链接：</label>
            <textarea rows="4" name="xianyu" maxlength="250" required id="id_xianyu">{{ form.cleaned_data.xianyu|default_if_none:"" }}</textarea>
        </div>
        <div class="field">
            <label>其他信息：</label>
            {{ form.note }}
        </div>
        <input class="ui pink button" type="submit" value="提交">
        售出后请及时删除出票信息
    </form>
</div>
{% endblock %}

yyj/templates/yyj/chupiao_search.html
{% extends "yyj/base.html" %}

{% block title %}搜索演出信息{% endblock %}

{% block content %}
<div class="ui basic segment">
  <h3 class="ui pink header">搜索演出信息</h3>
  <form class="ui form" action="{% url 'yyj:yyj.chupiao_search' %}" method="get">
    <div class="inline fields">
        <label>音乐剧：</label>
        <div class="field">{{ form.keyword }}</div>
        <label>日期：</label>
        <div class="field"><input type="date" name="date" id="id_date" value="{{ form.cleaned_data.date|date:'Y-m-d' }}" required></div>
        <input class="ui pink button" type="submit" value="搜索">
    </div>
  </form>
    {% if show_list %}
        {% for show in show_list %}
            <div class="ui card">
                <div class="content">
                    <div class="header">
                        <a href="{{ show.schedule.tour.musical.get_absolute_url }}" target="_blank">{{ show.schedule.tour.musical.name }}</a>
                    </div>
                    <div class="description">
                        <a href="{{ show.schedule.stage.theatre.city.get_absolute_url }}" target="_blank">{{ show.schedule.stage.theatre.city.name }}</a>
                        <a href="{{ show.schedule.stage.get_absolute_url }}" target="_blank">
                            {{ show.schedule.stage.theatre.name }}{{ show.schedule.stage.name|default_if_none:"" }}
                        </a><br>
                        {{ show.time|date:"n月j日 l H:i" }}<br>
                        {% for show_cast in show.cast_list %}
                        <a href="{{ show_cast.artist.get_absolute_url }}" target="_blank">{{ show_cast.artist.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <a class="ui bottom attached button" href="{% url 'yyj:yyj.chupiao_add' %}?show={{ show.id }}"><i class="add icon"></i> 出票 </a>
            </div>
        {% endfor %}
    {% endif %}
</div>
<script>
$("[data-label='chupiao']").attr("class","active item");
</script>
{% endblock %}

yyj/templates/yyj/donation.html
{% extends "yyj/base.html" %}

{% block title %}捐赠名单{% endblock %}

{% block content %}
<div class="ui basic segment">
    <h2 class="ui pink header">感谢捐赠</h2>
    <div class="ui bulleted list">
        <div class="item"><a href="https://apps.apple.com/cn/app/记录现场/id6502620974" target="_blank">记录现场App</a>（2025.6.13）</div>
    </div>
    <p>捐赠款项已全部用于域名续费。</p>
</div>
{% endblock %}

yyj/templates/yyj/download.html
{% extends "yyj/base.html" %}

{% block title %}数据下载{% endblock %}

{% block content %}
<div class="ui basic segment">
    <h2 class="ui pink header">数据下载</h2>
    <p>
        若Windows系统Excel打开csv格式文件时乱码，可采用以下两种方式解决：
        <br>1. 打开Excel，工具栏“数据”→“从文本/CSV”，选择文件后，修改“文件原始格式”为“Unicode(UTF-8)”，加载。
        <br>2. 右键csv文件→打开方式→记事本，“文件”→“另存为”，修改“编码”为“带有BOM的UTF-8”，保存。
    </p>
    1. csv格式演出详情（时间、城市、音乐剧、卡司、剧院）<br>
    例：2023-07-01 14:00,上海,XXX剧,A演员 B演员 C演员,XX剧场<br>
    {% for file in file_list %}
    <a href="{% url 'yyj:yyj.download_file' file.name %}">{{ file.description }}</a>
    {{ file.count }}场<br>
    {% endfor %}
    <br>
    2. csv格式音乐剧信息（音乐剧、原创性、进度、其他信息、制作公司、主创信息）<br>
    例：XXX剧,原创,上演,根据XXX文学作品改编,出品：XXX公司,编剧作词：AAA 作曲：BBB<br>
    <a href="{% url 'yyj:yyj.download_file' 'musical.csv' %}">音乐剧信息</a>
    {{ count }}部<br>
</div>
{% endblock %}

yyj/templates/yyj/location_map.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <title>{{ location.name }}</title>
    <link rel="stylesheet" type="text/css" href="https://lib.baomitu.com/semantic-ui/2.4.1/semantic.min.css">
    <script crossorigin="anonymous" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" src="https://lib.baomitu.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://lib.baomitu.com/semantic-ui/2.4.1/semantic.min.js"></script>
    <script type="text/javascript">
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "pd2xw84n9i");
    </script>
    <script type="text/javascript" src="http://api.tianditu.gov.cn/api?v=4.0&tk=8d1a33b8e3c82d468e7399fe50a6a1db"></script>
    <script src="http://lbs.tianditu.gov.cn/js/lib/d3/d3.min.js" charset="utf-8"></script>
    <script src="http://lbs.tianditu.gov.cn/api/js4.0/opensource/openlibrary/D3SvgOverlay.min.js"></script>
    <style type="text/css">
        html, body {
            height: 100%;
        }
        #map-canvas {
            height: 100%;
        }
    </style>
</head>
<body>
<div id="map-canvas"></div>
<script>
    var map = new T.Map("map-canvas");
    map.centerAndZoom(new T.LngLat({{ location.longitude }}, {{ location.latitude }}), 18);
    var marker = new T.Marker(new T.LngLat({{ location.longitude }}, {{ location.latitude }}));
    map.addOverLay(marker);
    var content ="<a href='{{ location.get_absolute_url }}' target='_blank'>{{ location.name }}</a>";
    var markerInfoWin = new T.InfoWindow(content);
    marker.addEventListener("click", function () {
        marker.openInfoWindow(markerInfoWin);
    });
</script>
</body>
</html>

yyj/templates/yyj/produce_detail.html
{% extends "yyj/base.html" %}

{% block title %}{{ produce.name }}{% endblock %}

{% block content %}
<div class="ui basic segment"><h2 class="ui header">{{ produce.name }}</h2></div>
{% if musical_produce_list %}
<table class="ui pink single line unstackable compact table">
    <thead>
    <tr><th>参与度</th><th>剧目</th><th>原创性</th><th>进度</th><th>首演日期</th><th>其他信息</th></tr>
    </thead>
    <tbody>
    {% for musical_produce in musical_produce_list %}
    <tr>
        <td>{{ musical_produce.title }}</td>
        <td><a href="{{ musical_produce.musical.get_absolute_url }}">{{ musical_produce.musical.name }}</a></td>
        <td>{% if musical_produce.musical.is_original %}原创{% else %}引进{% endif %}</td>
        <td>{{ musical_produce.musical.get_progress_display }}</td>
        <td>{% if musical_produce.musical.premiere_date_text %}{{ musical_produce.musical.premiere_date_text }}{% else %}{{ musical_produce.musical.premiere_date }}{% endif %}</td>
        <td>{{ musical_produce.musical.info }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

yyj/templates/yyj/show_year_index_artist.html
{% extends "yyj/base.html" %}

{% block title %}{{ year }}年演出{% endblock %}

{% block content %}
<p>
<div class="ui right floated buttons">
    <a href="{% url 'yyj:yyj.show_year_index' year %}" class="ui pink basic button">
       按音乐剧查询
    </a>
    <a href="{% url 'yyj:yyj.show_year_index_city' year %}" class="ui pink basic button">
       按城市查询
    </a>
</div>
    <br>&nbsp;&nbsp;&nbsp;&nbsp;演员：{{ artist_list.paginator.count }}人
</p>
<table class="ui pink unstackable table">
    <thead>
    <tr>
        <th>演员</th>
        <th class="single line">场次</th>
        <th>详情</th>
    </tr>
    </thead>
    <tbody>
    {% for artist in artist_list %}
    <tr class="top aligned">
        <td><h4 class="ui header"><a href="{{ artist.get_absolute_url }}" target="_blank">{{ artist.name }}</a></h4></td>
        <td>{{ artist.show_count }}</td>
        <td>
            {% for cast in artist.cast_list %}
                <a href="{{ cast.role.musical.get_absolute_url }}" target="_blank">{{ cast.role.musical.name }}</a>
                {{ cast.role.name }}
                {{ cast.num_show }}场
                <br>
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if artist_list.paginator.num_pages > 1 %}
<div class="ui pagination menu">
    {% for page in artist_list.paginator.page_range %}
        {% if artist_list.number == page %}
            <a href="?page={{ page }}" class="active item">{{ page }}</a>
        {% else %}
            <a href="?page={{ page }}" class="item">{{ page }}</a>
        {% endif %}
    {% endfor %}
</div>
{% endif %}
<script>
{% if year %}
    $("[data-label='year']").text("{{ year }}年");
{% else %}
    $("[data-label='all']").attr("class","active item");
{% endif %}
</script>
{% endblock %}